version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "@Shopify/functions-dependabot-reviewers"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
    registries: "*"
    reviewers:
      - "@Shopify/functions-dependabot-reviewers"
