[package]
name = "example_with_targets"
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
shopify_function = { path = "../shopify_function", version = "0.4.0" }
serde = { version = "1.0.13", features = ["derive"] }
serde_json = "1.0"
graphql_client = "0.13.0"
